databases:
  - name: Homologation
    databaseName: managers_msa
    user: root

services:
  - type: web
    name: managersa
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn managersa.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: managersa
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4